### ISSUE TITLE
problem using Spec Augment for a sphere file

### ISSUE THREAD

**Issue by hc038** [irebai/SpecAugment_KALDI#3]
@irebai firstly, very thankful for your work.
I am using fisher corpus. the data here is in the form of .sph files, each sphere file has about 100 utterances in it. when i do spec-augmentation features are only getting generated for some utterances say 50 out of 100 and throwing an error.
here attaching is tail part in the log file

![image](https://user-images.githubusercontent.com/73985177/110091997-1d602d80-7dbf-11eb-9cca-35fbcbef6b74.png)

**Comment by irebai** [comment]
@hc038 
I'm sorry for my late response.
Since you closed the issue, could you please specify what was the real issue ?
Thanks
